source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sqlite3'
gem 'devise'
gem 'sass-rails', '~> 4.0.2'
gem 'react-rails'
gem 'rails_12factor', group: :production
gem "rails-erd"
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'therubyracer', platforms: :ruby
gem 'quill-rails', '~> 0.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem "font-awesome-rails"

group :doc do
	gem 'sdoc', require: false
end

group :development, :test do
	gem 'faker'
end

